#!/bin/bash

set -e

if [ "$TRAVIS" = "true" ]; then
  echo '$ sudo apt-get install bc' && echo ''
  sudo apt-get install -q -q bc 2> /dev/null > /dev/null
fi

t/sizes index.js redux.js

echo ""

(proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  echo ""
  echo "minified"
  echo ""
  default=$(cat redux.js | uglifyjs | gzip -c | wc -c)
  lift=$(cat redux.js | uglifyjs --lift-vars | gzip -c | wc -c)

  bak=index-$(date +'%FT%T').js
  mv redux.js $bak
  if [ $default -lt $lift ]; then
    cat $bak | uglifyjs > redux.js
  else
    cat $bak | uglifyjs --lift-vars > redux.js
  fi 
 
  (proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1
fi

echo ""
